### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string On Basic Setup

### ISSUE THREAD

**Issue by btotharye** [jfrog/terraform-provider-pipeline#18]
**Describe the bug**
When trying to do the terraform apply for a very basic pipeline_project_integration resource I continue to get the plugin crashing with the below information, I have validated my token I'm using can hit the license api and has all the rights it should but I'm not sure what this panic is coming from and was hoping someone could shed some light on this.  I basically can't use the plugin at all atm, it always crashes with this error and I'm not sure how to find more information on it.

The basic TF snippet

```
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "6.16.0"
    }
    pipeline = {
      source  = "registry.terraform.io/jfrog/pipeline"
      version = "1.1.0"
    }
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "pipeline" {
  url           = "${var.artifactory_url}"
  check_license = true
  access_token  = xxx

resource "pipeline_project_integration" "test-integration" {
  name                    = "test-integration"
  project_id              = 0
  project                 = {
      name = "test-project"
  }
  master_integration_id   = 0
  master_integration_name = "test-integration"
  environments            = ["DEV"]
  is_internal             = false

  form_json_values {
    label = "IsJFrogPipe"
    value = "true"
  }
}
```

```
pipeline_project_integration.test-integration: Creating...
╷
│ Error: Request cancelled
│
│   with pipeline_project_integration.test-integration,
│   on pipelines.tf line 1, in resource "pipeline_project_integration" "test-integration":
│    1: resource "pipeline_project_integration" "test-integration" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with pipeline_node_pool.on-demand-node-pool,
│   on pipelines.tf line 18, in resource "pipeline_node_pool" "on-demand-node-pool":
│   18: resource "pipeline_node_pool" "on-demand-node-pool" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-pipeline_v1.1.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 48 [running]:
github.com/jfrog/terraform-provider-pipeline/pkg/pipeline.pipelineProjectIntegrationResource.func1(0x140003086c8?, {0x101505623?, 0xb?})
	github.com/jfrog/terraform-provider-pipeline/pkg/pipeline/resource_pipeline_project_integration.go:128 +0xe8
github.com/jfrog/terraform-provider-pipeline/pkg/pipeline.pipelineProjectIntegrationResource.func3(0x14000114580)
	github.com/jfrog/terraform-provider-pipeline/pkg/pipeline/resource_pipeline_project_integration.go:155 +0x148
github.com/jfrog/terraform-provider-pipeline/pkg/pipeline.pipelineProjectIntegrationResource.func6({0x10179fb58, 0x14000300600}, 0x14000114580, {0x10178f580?, 0x140004f41e0?})
	github.com/jfrog/terraform-provider-pipeline/pkg/pipeline/resource_pipeline_project_integration.go:200 +0xe4
github.com/jfrog/terraform-provider-shared/util.applyTelemetry.func1({0x10179fb58?, 0x14000300600}, 0x0?, {0x10178f580?, 0x140004f41e0})
	github.com/jfrog/terraform-provider-shared@v1.4.0/util/util.go:225 +0x1d4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140002aca80, {0x10179fb90, 0x14000080330}, 0xd?, {0x10178f580, 0x140004f41e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140002aca80, {0x10179fb90, 0x14000080330}, 0x14000241930, 0x14000114380, {0x10178f580, 0x140004f41e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0x874
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140003fe5a0, {0x10179fae8?, 0x14000510580?}, 0x14000513770)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xb94
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140003910e0, {0x10179fb90?, 0x1400050d890?}, 0x14000153ce0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x38c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10176b080?, 0x140003910e0}, {0x10179fb90, 0x1400050d890}, 0x14000507ce0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002908c0, {0x1017a2530, 0x14000318820}, 0x140005cfb00, 0x140004125d0, 0x101c0e740, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xb3c
google.golang.org/grpc.(*Server).handleStream(0x140002908c0, {0x1017a2530, 0x14000318820}, 0x140005cfb00, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x298

Error: The terraform-provider-pipeline_v1.1.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Artifactory Version:

```
{
  "version" : "7.41.4",
  "revision" : "74104900"
  }
}%
```

Terraform Version with Provider Versions:

```
Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.43.0
+ provider registry.terraform.io/hashicorp/vault v3.11.0
+ provider registry.terraform.io/jfrog/artifactory v6.16.0
+ provider registry.terraform.io/jfrog/pipeline v1.1.0
```

**Requirements for and issue**
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform

**Expected behavior**
I would expect it to not crash and apply the code, this doesn't happen on the plan stage it works on plan stage and shows its going to create the resource correctly, but then when applying it gets to this part and crashes.

**Comment by alexhung** [comment]
@btotharye In the meantime you can pin your provider version to 1.0.5. My suspicion is that yesterday 1.1.0 release introduces this bug.

**Comment by btotharye** [comment]
ok I think I had the same issue on that version but I'll test and let you know, I was even having this issue on the simple data project part.

What is it considering a project in this pipeline setup tho?  I don't see a mention of projects in the UI for pipelines.

**Comment by alexhung** [comment]
@btotharye Good to know. I'll report back once I have more info.

**Comment by alexhung** [comment]
@btotharye See [Projects documentation](https://www.jfrog.com/confluence/display/JFROG/Projects). It's a platform level concept that applies to Artifactory, Xray, Pipeline, etc.

**Comment by btotharye** [comment]
> Projects documentation

ah didn't realize it worked like that, that probably is why I"m having issues then we don't have a project setup in the dev env where we are testing this.

**Comment by alexhung** [comment]
@btotharye Not dumb question at all. Yes it should work. Looks like a bug in the data source.

**Comment by btotharye** [comment]
ok sorry last question, cause I set this all up in the UI first to confirm things, we use bitbucket for the integration along with kubernetes but I don't see a way to do these in the terraform provider, am I wrong on that?  I thought it would be the https://registry.terraform.io/providers/jfrog/pipeline/latest/docs/resources/project_integration#master_integration_id or no?  I just don't see a way to do the bitbucket stuff like I see in the UI for the bitbucket integration.  Sorry if I'm misunderstanding something.

**Comment by btotharye** [comment]
> @btotharye Not dumb question at all. Yes it should work. Looks like a bug in the data source.

and that data source for the pipeline_project should be the key not the full project name right?

**Comment by btotharye** [comment]
so I've tried doing this to even create the pipeline and such and if I leave the data part in it always fails, but this lets the plan part at least work but then when I go to apply I get that same crash before about the `interface {} is nil, not string`.

```
resource "project" "pipe-test" {
  key = "pipe"
  display_name = "Pipeline Test"
  description = "Pipeline Test"
  admin_privileges {
    manage_members   = true
    manage_resources = true
    index_resources  = true
  }
}

resource "pipeline_project_integration" "test-integration" {
  name                    = "shared-infra-dev-eks-integration"
  project                 = {
      name = "pipe"
  }
  master_integration_id   = 0
  master_integration_name = "shared-infra-dev-eks-integration"
  environments            = ["DEV"]
  is_internal             = false

  form_json_values {
    label = "IsJFrogPipe"
    value = "true"
  }
}

resource "pipeline_node_pool" "on-demand-node-pool" {
  name                       = "on-demand-node-pool-ubun-20-04"
  project_id                 = 0
  number_of_nodes            = 5
  is_on_demand               = true
  architecture               = "x86_64"
  operating_system           = "Ubuntu_20.04"
  node_idle_interval_in_mins = 20
  environments               = ["DEV"]
}
```

So not sure if I"m doing something wrong here or what, I have the providers all setup right in the providers file too that part all works ok.  This should work the way I have it setup right or do I have to use references to the object that is built in the resources section at the top for the project?

**Comment by alexhung** [comment]
@btotharye Ok so what I found are these:

1. In data source `pipeline_project.name`, you need to use the Project's *name*. Not the key. In my test, I have a project called "My Project" with key "myproj".

No error when I defined the data source using the name:

```hcl
data "pipeline_project" "my-project" {
  name = "My Project"
}
```

This needs to be documented as well as code make more robust (i.e. return error message vs crashing).

2. In resource `pipeline_project_integration`, the `project` attribute doesn't actually seem to map to anything useful. Instead you should use the `project_id` attribute and set it with value from the data source:

```hcl
data "pipeline_project" "my-project" {
  name = "My Project"
}

resource "pipeline_project_integration" "test-integration" {
  name                    = "test-integration"
  project_id              = data.pipeline_project.my-project.id
  master_integration_id   = 0
  master_integration_name = data.pipeline_project.my-project.name
  environments            = ["DEV"]
  is_internal             = false

  form_json_values {
    label = "IsJFrogPipe"
    value = "true"
  }
}
```
Similarly, we need to remove the support of the `project` attribute map since it is unnecessary.

Hope this helps you move forward while we work on the fix.

**Comment by btotharye** [comment]
Sounds good I'll give it a test.

**Comment by alexhung** [comment]
@btotharye Actually you can still use the `project` attribute. It requires both `key` and `name` attributes be set. Otherwise you run into the panic crash. I'm working on improving that.
